---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: smb-prodbe-logs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: backend_volume_logs_prod # make sure it's a unique id in the cluster
    volumeAttributes:
      source: "//10.128.12.8/prodbackend/logs/"
    nodeStageSecretRef:
      name: smbcreds-prodbe
      namespace: prod
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-smb-prodbe-logs
  namespace: prod
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: smb-prodbe
  storageClassName: smb
