apiVersion: v1
kind: Service
metadata:
  name: backend-prisma-service
  namespace: prod
  labels:
    app: prisma
    tier: backend
  annotations:
    linkerd.io/inject: "enabled"
spec:
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  selector:
    app: prisma
    tier: backend