apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-prisma
  namespace: prod
  labels:
    app: prisma
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prisma
      tier: backend
  template:
    metadata:
      name: backend-prisma
      labels:
        app: prisma
        tier: backend
    spec:
      containers:
        - name: backend-prisma
          image: jensdl/backend:prod.v22.11.21-19h27m
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: MYSQL_HOST
              value: 'mysql-service'
---
apiVersion: v1
kind: Service
metadata:
  name: backend-prisma-service
  namespace: prod
  labels:
    app: prisma
    tier: backend
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8081
  selector:
    app: prisma
    tier: backend
  template:
    spec:
      containers:
        - image: jensdl/backend:prod.v22.11.21-19h27m
