apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-prisma
  namespace: prod
  labels:
    app: prisma
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prisma
      tier: backend
  template:
    metadata:
      name: backend-prisma
      labels:
        app: prisma
        tier: backend
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
        - name: backend-prisma
          image: jensdl/backend:prod.v22.12.16
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            #- name: MYSQL_HOST

            #  value: 'mysql-service'
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-service/prismaDb?"
            - name: SPRING_DATASOURCE_USERNAME
              value: "user"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "password"
            - name: SPRING_MAIL_USERNAME
              value: "prisma.pxl@gmail.com"
            - name: SPRING_MAIL_PASSWORD
              value: "axtyodwkimshxrim"
          volumeMounts:
            - name: smb-prodbe-logs
              mountPath: "/logs"
              readOnly: false
            - name: smb-prodbe-files
              mountPath: "/.data"
              readOnly: false
      volumes:
        - name: smb-prodbe-logs
          persistentVolumeClaim:
            claimName: pvc-smb-prodbe-logs
        - name: smb-prodbe-files
          persistentVolumeClaim:
            claimName: pvc-smb-prodbe-files
