---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-proddb
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/nfs_mount//data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-local-proddb
  namespace: prod
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: local-proddb
