---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-proddb
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.128.12.8
    path: "/mnt/K3S/Prisma/prod/database/sql_data/data/"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nfs-proddb
  namespace: prod
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: nfs-proddb
