apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: prod
spec:
  selector:
    matchLabels:
      app: prisma
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prisma
        tier: database
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
        - image: jensdl/mysql:dev.v22.12.08-12h17m
          imagePullPolicy: IfNotPresent
          name: mysql
          env:
            # Use secret in real usage
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: database
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: root_password
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: user_password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: nfs-devdb
              mountPath: "/var/lib/mysql/"
              readOnly: false
      volumes:
        - name: nfs-devdb
          persistentVolumeClaim:
            claimName: pvc-nfs-proddb
