---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: prod
type: Opaque
data:
  user: dXNlcg==
  user_password: cGFzc3dvcmQ=
  database: cHJpc21hRGI=
  root_password: YWRtaW4=
