apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-nginx-ingress
  namespace: dev
spec:
  rules:
  - host: dev.backend.prisma.orcraft.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backend-prisma-service
            port:
              number: 8081
  tls:
    - hosts:
        - dev.backend.prisma.orcraft.net
      secretName: dev.backend.prisma-tls