apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-nginx-ingress
  namespace: dev
  annotations:
    kubernetes.io/ingress.class: "traefik"
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: dev.backend.prisma.orcraft.net
    http:
      paths:
      - path: /
        backend:
          service:
            name: backend-prisma-service
            port:
              number: 8081