apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-prisma
  namespace: dev
  labels:
    app: prisma
    tier: backend
    tags.datadoghq.com/env: dev
    tags.datadoghq.com/service: backend-prisma
    tags.datadoghq.com/version: latest
  annotations:
    ad.datadoghq.com/backend-prisma.logs: '[{"source": "backend-prisma","service": "backend-prisma","tags": ["env:dev"]}]'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prisma
      tier: backend
  template:
    metadata:
      name: backend-prisma
      labels:
        app: prisma
        tier: backend
        tags.datadoghq.com/env: dev
        tags.datadoghq.com/service: backend-prisma
        tags.datadoghq.com/version: latest
        admission.datadoghq.com/enabled: "true"
      annotations:
        linkerd.io/inject: enabled
        admission.datadoghq.com/java-lib.version: v1.2.0
    spec:
      containers:
        - name: backend-prisma
          image: jensdl/testimage:backend2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
            - containerPort: 8126
          env:
            #- name: MYSQL_HOST

            #  value: 'mysql-service'
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-service/prismaDb?"
            - name: SPRING_DATASOURCE_USERNAME
              value: "user"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "password"
            - name: SPRING_MAIL_USERNAME
              value: "prisma.pxl@gmail.com"
            - name: SPRING_MAIL_PASSWORD
              value: "axtyodwkimshxrim"
            - name: DD_PROFILING_ENABLED
              value: "true"
            - name: DD_LOGS_INJECTION
              value: "true"
            - name: DD_APPSEC_ENABLED
              value: "true"
            - name: DD_TRACE_SAMPLE_RATE
              value: "1"
          volumeMounts:
            - name: smb-devbe-logs
              mountPath: "/logs"
              readOnly: false
            - name: smb-devbe-files
              mountPath: "/.data"
              readOnly: false
      volumes:
        - name: smb-devbe-logs
          persistentVolumeClaim:
            claimName: pvc-smb-devbe-logs
        - name: smb-devbe-files
          persistentVolumeClaim:
            claimName: pvc-smb-devbe-files
