apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-prisma
  namespace: dev
  labels:
    app: prisma
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prisma
      tier: backend
  template:
    metadata:
      name: backend-prisma
      labels:
        app: prisma
        tier: backend
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
        - name: backend-prisma
          image: jensdl/backend:dev.v22.12.13-14h48m
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            #- name: MYSQL_HOST
            #  value: 'mysql-service'
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-service/prismaDb?"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: user_password
            - name: SPRING_MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: email_username
            - name: SPRING_MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: email_password
          volumeMounts:
            - name: smb-devbe-logs
              mountPath: "/logs"
              readOnly: false
            - name: smb-devbe-files
              mountPath: "/.data"
              readOnly: false
      volumes:
        - name: smb-devbe-logs
          persistentVolumeClaim:
            claimName: pvc-smb-devbe-logs
        - name: smb-devbe-files
          persistentVolumeClaim:
            claimName: pvc-smb-devbe-files
