apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-prisma
  namespace: dev
  labels:
    app: prisma
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prisma
      tier: backend
  template:
    metadata:
      name: backend-prisma
      labels:
        app: prisma
        tier: backend
    spec:
      containers:
        - name: backend-prisma
          image: jensdl/backend:dev.v22.12.08-14h27m
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: MYSQL_HOST
              value: 'mysql-service'
          volumeMounts:
            - name: smb-devbe
              mountPath: "/logs"
              readOnly: false
      volumes:
        - name: smb-devbe
          persistentVolumeClaim:
            claimName: pvc-smb-devbe
