apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: dev
spec:
  ports:
    - port: 3306
  selector:
    app: prisma
    tier: database
  template:
    spec:
      containers:
        - image: jensdl/mysql:dev.v22.11.20-10h28m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: dev
spec:
  selector:
    matchLabels:
      app: prisma
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prisma
        tier: database
    spec:
      containers:
        - image: jensdl/mysql:dev.v22.11.20-10h28m
          imagePullPolicy: IfNotPresent
          name: mysql
          env:
            # Use secret in real usage
            - name: MYSQL_DATABASE
              value: 'prismaDb'
            - name: MYSQL_ROOT_PASSWORD
              value: 'admin'
            - name: MYSQL_USER
              value: 'user'
            - name: MYSQL_PASSWORD
              value: 'password'
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pv-claim
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    app: prisma
spec:
  storageClassName: manual
  claimRef:
    name: mysql-pv-claim
    namespace: dev
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/ubuntu/sql_data"
  template:
    spec:
      containers:
        - image: jensdl/mysql:dev.v22.11.20-10h28m
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: dev
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  template:
    spec:
      containers:
        - image: jensdl/mysql:dev.v22.11.20-10h28m
