---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-devdb
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.128.12.8
    path: "/mnt/K3S/Prisma/dev/database/sql_data/data/"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-local-devdb
  namespace: dev
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: local-devdb
