apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: dev
spec:
  selector:
    matchLabels:
      app: prisma
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prisma
        tier: database
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
        - image: jensdl/mysql:dev.v22.12.23-10h14m
          imagePullPolicy: IfNotPresent
          name: mysql
          env:
            # Use secret in real usage
            - name: MYSQL_DATABASE
              value: 'prismaDb'
            - name: MYSQL_ROOT_PASSWORD
              value: 'admin'
            - name: MYSQL_USER
              value: 'user'
            - name: MYSQL_PASSWORD
              value: 'password'
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: nfs-devdb
              mountPath: "/var/lib/mysql/"
              readOnly: false
      volumes:
        - name: nfs-devdb
          persistentVolumeClaim:
            claimName: pvc-nfs-devdb
