apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: dev
spec:
  ports:
    - port: 3306
  selector:
    app: prisma
    tier: database
  template:
    spec:
      containers:
        - image: jensdl/mysql:dev.v22.11.26-17h54m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: dev
spec:
  selector:
    matchLabels:
      app: prisma
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prisma
        tier: database
    spec:
      containers:
        - image: jensdl/mysql:dev.v22.11.26-17h54m
          imagePullPolicy: IfNotPresent
          name: mysql
          env:
            # Use secret in real usage
            - name: MYSQL_DATABASE
              value: 'prismaDb'
            - name: MYSQL_ROOT_PASSWORD
              value: 'admin'
            - name: MYSQL_USER
              value: 'user'
            - name: MYSQL_PASSWORD
              value: 'password'
          ports:
            - containerPort: 3306
              name: mysql
